### ISSUE TITLE
A4 Printing enhancements

### ISSUE THREAD

**Issue by axel9546** [yonixw/MangaPrinter#20]
### 🧙‍♂️ Feature request
Automation tools to help you print in A4, best quality, mantaining the property of RTL reading.

### 📝 Additional context
It would be awesome, if we could just import our Volume/Chapter folder, and print, like it was a tankobon, but in A4 size.
Then the software could:
- upscale the images to get best printing quality for A4 (like waifu2x)
- No booklet, but just full A4 size, double-sided printing
- adjusted contrast ratio to paper

**Comment by yonixw** [comment]
Hi, thanks for the suggestions.

I have a few questions:
1. By saying "automation", do you mean adding a CLI option (another option that doesn't require user interaction with a GUI)? but the same functionality? to be automated to use in shell/bat scripts?
2. By saying "just full A4 size", what do you suggest to be implemented? The PDF can be exported today to any size, A4 included.
3. Can you give an example of "adjusted contrast ratio to paper"? Maybe before/after or even better what tool you want to mimic. Like a specific Photoshop or GIMP plugins.

Thanks in advance.

But just a note, this is a hobby project and implementation of these enhancements may take a long time.

**Comment by axel9546** [comment]
Thanks so much for having interest on this.
In short, goal is to take a digital image file JPG or whatever, and print it to A4 size, 1 image per page. (so it's not a booklet)

Imagine having a tankobon, but A4 size.
With this in mind, what idea comes to you for taking original cbr/cbz digital file, or files with images inside, and turn them into a unique, ready made A4 printable file?

**Comment by yonixw** [comment]
Hi, I thought about the scope of this project, particularly what I can support in the future and what this project is meant to solve.

As a result, I will not be supporting AI image processors such as waifu2x at this time because the problems associated with running those or connecting to some Web APIs for those are beyond my scope of support.

In addition, I will not be supporting any automation (CLI) at this time.
Because, while the goal of this project remains to assist in the resolution of printing problems, which we will undoubtedly want to automate whenever possible, there will always be cases where only a GUI can assist. As in determining whether a detected "too much ink" warning is a real file that needs to be deleted or if it is simply artwork added by the manga author (as in one piece, every few chapters).

What I do intend to support:
1. Choosing any page size: I'll make it possible to change it in the configuration, which will be tracked in #12.
2. ~~I agree that the CBZ import option, which is now tracked in #28, should be added.~~

What I may support in the future (low priority):
1. Image fixes such as contrast and brightness. Currently can be done with preprocessing cli such as [magick](https://imagemagick.org/script/command-line-tools.php) or with any print dialog. Edit: Done in 2de3d7a

Thanks again.
