### ISSUE TITLE
Running on linux?

### ISSUE THREAD

**Issue by ghost** [yonixw/MangaPrinter#5]
I'm using arch. Is there a way to make this run on linux? Wine throws a lot of errors.
Thanks!

**Comment by yonixw** [comment]
Currently no. If I will find a simple way to run\migrate it I will comment here.

But maybe this will help:
https://ccifra.github.io/PortingWPFAppsToLinux/Overview.html

**Comment by yonixw** [comment]
Notes for myself:
* UI (XAML):
  * Tried to convert UI for web with [OpenSilver](https://opensilver.net/) but the xaml was too limited
  * [Avalonia ](https://avaloniaui.net/)might be easy enough to convert UI but won't work for ARM\Mobile our of the box ([see here](https://stackoverflow.com/a/59704058/1997873))

* Backend (logic)
  * Tried to convert to .NET Core but since we really need to convert `ImageMagick -> Windows Bitmap` we will need windows only libs and can't run .net-core on linux ([see here](https://stackoverflow.com/questions/58116849/can-i-compile-net-core-3-wpf-application-in-linux) and even clearer [here](https://github.com/dlemstra/Magick.NET/issues/547)).

**Comment by ghost** [comment]
Hey! Were you able to make any progress on this? Happy new year :)

**Comment by yonixw** [comment]
~~I'm currently rewriting in react+.net core... but it will take a couple o month to get it ready... so for now no...~~
Waiting for traction on this request

**Comment by ghost** [comment]
Thanks so much for your effort :) Is there any way to emulate the program with wine to make it work as it is now?

**Comment by yonixw** [comment]
It took me some time but I was able to level up my skills and make it work on Linux, I have prepared a docker that can run it. You can see the instructions here:

https://github.com/yonixw/MangaPrinter/blob/master/LinuxDockers/README.md

And a demo of it here:

https://youtu.be/nQXFGGVf52Y
